# Generated by Django 4.2.4 on 2023-08-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
