# Generated by Django 4.2.4 on 2023-08-25 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_coin_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coin",
            options={"verbose_name": "Coin"},
        ),
        migrations.AlterUniqueTogether(
            name="coin",
            unique_together={("symbol", "date")},
        ),
    ]
