# Generated by Django 4.2.15 on 2024-08-27 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_customuser_gameboard_gameplay_player_delete_coin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="board",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board",
                to="api.gameboard",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="gameplay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gameplay",
                to="api.gameplay",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
