# Generated by Django 4.2.15 on 2024-08-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_player_board_alter_player_gameplay_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="user",
        ),
        migrations.AddField(
            model_name="player",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
